version: '3.8'

services:
  proaula-app:
    build: .
    container_name: proaula_app_container
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/proAulaMongo
      - SPRING_DATA_REDIS_HOST=redis_cache
      - SPRING_SESSION_STORE_TYPE=redis
      # - SPRING_DATA_REDIS_PASSWORD=tu_password_si_aplica
    depends_on:
      - mongo_db
      - redis_cache
    networks:
      - proaula-network
    volumes:
      - ./uploads:/app/uploads
  mongo_db:
    image: mongo:latest
    container_name: proaula_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proaula-network

  redis_cache:
    image: redis:latest
    container_name: proaula_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - proaula-network
    # command: redis-server --requirepass tucontrasenasegura

volumes:
  mongo-data:
  redis-data:

networks:
  proaula-network:
    driver: bridge